#!/usr/bin/env bash

mkdir -p ~/.config/nvim
mkdir -p ~/.config/i3

ln -s ./neovim ~/.config/nvim
ln -s ./i3 ~/.config/i3


#for f in `find . -regex ".*\.vim$\|.*\.lua$"`; do
#    rm -rf ~/.config/nvim/$f
#    ln -s ~/code/dotfiles/dev-env/$f ~/.config/nvim/$f
#done
