#!/usr/bin/env bash

mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua
mkdir -p ~/.config/rofi

mkdir -p ~/.config/i3

for f in `find ./neovim -regex ".*\.vim$\|.*\.lua$"`; do
    f=$(basename $f)
    #echo "neovim: $f"
    rm -rf ~/.config/nvim/$f
    ln -s ~/code/dotfiles/dev-env/neovim/$f ~/.config/nvim/$f
done

for f in ./i3/*; do
    f=$(basename $f)
    #echo "i3: $f"
    rm -rf ~/.config/i3/$f
    ln -s ~/code/dotfiles/dev-env/i3/$f ~/.config/i3/$f
done

if [ ! -f ~/.config/rofi/config.rasi ]; then
   ln -s ~/code/dotfiles/dev-env/rofi/config.rasi ~/.config/rofi/config.rasi
fi
